version: "3"

services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: 'panel'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 8081:3306
    restart: always

  panel:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: always
    depends_on:
      - database
