version: "3"

services:
  panel:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'panel'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ../mysql-data:/var/lib/mysql
    restart: always
