version: "3"

services:
  panel:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: always
    depends_on:
      - database

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: 'panel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ../mysql-data:/var/lib/mysql
    ports:
      - 8081:3306
    restart: always
