version: "2.1"

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'panel'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    healthcheck:
      test: "exit 0"

  panel:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: always
    depends_on:
      database:
        condition: service_healthy
